$schema: https://adapt2.sis.pitt.edu/cupcake/schemas/code-completion/0.1.0
source: main.py
license: MIT
locale: en
id: cc_py_range_three_1
title: Printing Sequence of Numbers with a Gap Between Adjacent Values
description: Construct a program that prints a sequence of numbers from 7 (inclusive) to 35 (inclusive)
  in increments of 7.
authors:
- first: Kamil
  last: Akhuseyinoglu
  email: moh70@pitt.edu
  affiliation: University of Pittsburgh
pedagogy:
  activity: code-completion
  difficulty: novice
  prereq_topics: []
  topics: []
runtime:
  language: python
  version: 3
statement: Write a program that prints a sequence of numbers from 7 (inclusive) to 35 (inclusive) in increments
  of 7.
executions:
- title: Sample Run
  stdin: []
  stdout: |-
    7
    14
    21
    28
    35
  console: |-
    7
    14
    21
    28
    35
  stderr: ''
  status: pass
elements:
- type: blank
  location:
    snippet: 'for num in range(7, 36, 7):'
  choices:
  - snippet: 'for num in range(7, 36, 7):'
    role: solution
    explanations:
    - body: We need to repeat printing the numbers that are in a sequence from 7 (inclusive) to 35 (inclusive).
        To do this, we need to use a loop structure. We use for loops instead of a while loop because
        we need to repeat the loop a certain number of times, and for loops are best-suited in cases like
        this when we know ahead of time the number of times that we need to repeat the loop.<br><br>Here,
        we want a sequence of every seventh number beginning with 7 and continuing up to but not including
        36. We get this sequence by calling the function range(7,36,7).
    - body: The last number in the range function specifies how much to increase each successive integer
        in the sequence, if this is omitted then step defaults to 1. Since we want to print only every
        seventh number, we set the step to 7.<br><br>Note that all statements inside the loop need to
        be indented with respect to the loop header.
  - snippet: 'for num in range(7, 35, 7):'
    role: distractor
  - snippet: 'for num in range(7, 37, 6):'
    role: distractor
  - snippet: 'for num in range(35, 7, 7):'
    role: distractor
  - snippet: 'for num in range(7, 7, 36):'
    role: distractor
